import styles from '../styles/Home.module.scss';
import Head from "next/head";
import Button from "./components/button/button.jsx";
import Radio from "./components/radio/radio.jsx";
import Check from "./components/check/check.jsx";
import RadioButton from "./components/radioButton/radioButton.jsx";
import Select from "./components/select/select.jsx";
import Header from "./components/header/header.jsx";


export default function Home() {
  return (
    <>
      <Head>
        <title>NesxJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Select question={100}/>
          <div className={styles.header__and__content}>
            <Header text={'Великая отечественная война'}/>
            <div className={styles.content__container}>
              <div className={styles.content}>
                <div className={styles.question}>
                С именем какого князя связано объединение Галицкого и Волынского княжеств?
                </div>
                <div className={styles.answers}>
                  <RadioButton text={'Романа Мстиславича'}/>
                  <RadioButton text={'Романа Мстиславича'}/>
                  <RadioButton text={'Романа Мстиславича'}/>
                  <RadioButton text={'Романа Мстиславича'}/>
                </div>
                <div className={styles.buttons}>
                  <Button text={'Пропустить'}/>
                  <Button disabled text={'Ответить'}/>
                </div>
              </div>
            </div>
          </div>
      </main>
    </>
  );
}
